name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: "184.73.16.42"
          USER: "ubuntu"
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$EC2_HOST "
            sudo chown -R $USER:$USER /home/ubuntu/hello-world &&
            sudo usermod -aG docker $USER &&
            git config --global --add safe.directory /home/ubuntu/hello-world &&
            cd /home/ubuntu/hello-world &&
            git pull &&
            sudo docker build -t sampleapp . &&
            sudo docker run -d --name myapp_container -p 8080:80 sampleapp
          "
